# Generated by Django 4.2.9 on 2024-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONE_TO_ONE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(null=True),
        ),
    ]
