# Generated by Django 4.2.9 on 2024-02-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RELATIONS_APP', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='RELATIONS_APP.author'),
        ),
    ]
